// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToursAyacuchoPeruAPI.Infrastructure.Persistence;

#nullable disable

namespace ToursAyacuchoPeruAPI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ToursAyacuchoPeruDbContext))]
    [Migration("20260709010610_AddPackageImageUrl")]
    partial class AddPackageImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.BloqueosCuenta", b =>
                {
                    b.Property<int>("BloqueoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BloqueoId"));

                    b.Property<DateTime?>("FechaBloqueo")
                        .HasColumnType("DATETIME2(0)");

                    b.Property<DateTime?>("FechaDesbloqueo")
                        .HasColumnType("DATETIME2(0)");

                    b.Property<byte>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BloqueoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("UQ_BloqueosCuenta_UsuarioId");

                    b.ToTable("BloqueosCuenta", (string)null);
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Comprobante", b =>
                {
                    b.Property<Guid>("ComprobanteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnviadoCorreo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaEmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("PagoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ComprobanteId");

                    b.HasIndex("PagoId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Comprobantes_Pago");

                    b.ToTable("Comprobantes", (string)null);
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<string>("NumReferencia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PagoId");

                    b.HasIndex("ReservaId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Pagos_Reserva");

                    b.ToTable("Pagos", (string)null);
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.PaqueteTuristico", b =>
                {
                    b.Property<Guid>("PaqueteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("AsientosDisp")
                        .HasColumnType("int");

                    b.Property<int>("CapacidadTotal")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("DATE");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("PaqueteId");

                    b.ToTable("PaquetesTuristicos", (string)null);
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Resena", b =>
                {
                    b.Property<Guid>("ResenaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("Calificacion")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<Guid>("PaqueteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ResenaId");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("UsuarioId", "PaqueteId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Resenas_UsuarioPaquete");

                    b.ToTable("Resenas", (string)null);
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("CantAsientos")
                        .HasColumnType("int");

                    b.Property<byte>("ContReprogramacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("DATE");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("DECIMAL(10,2)");

                    b.Property<Guid>("PaqueteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ReservaId");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("IX_Reservas_UsuarioId");

                    b.HasIndex("UsuarioId", "PaqueteId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Reservas_PendienteUnicaPorPaquete")
                        .HasFilter("[Estado] = 'PENDIENTE_PAGO'");

                    b.ToTable("Reservas", (string)null);
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Usuarios_Correo");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.BloqueosCuenta", b =>
                {
                    b.HasOne("ToursAyacuchoPeruAPI.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Bloqueo")
                        .HasForeignKey("ToursAyacuchoPeruAPI.Domain.Entities.BloqueosCuenta", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BloqueosCuenta_Usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Comprobante", b =>
                {
                    b.HasOne("ToursAyacuchoPeruAPI.Domain.Entities.Pago", "Pago")
                        .WithOne("Comprobante")
                        .HasForeignKey("ToursAyacuchoPeruAPI.Domain.Entities.Comprobante", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Comprobantes_Pagos");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Pago", b =>
                {
                    b.HasOne("ToursAyacuchoPeruAPI.Domain.Entities.Reserva", "Reserva")
                        .WithOne("Pago")
                        .HasForeignKey("ToursAyacuchoPeruAPI.Domain.Entities.Pago", "ReservaId")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_Reservas");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Resena", b =>
                {
                    b.HasOne("ToursAyacuchoPeruAPI.Domain.Entities.PaqueteTuristico", "Paquete")
                        .WithMany("Resenas")
                        .HasForeignKey("PaqueteId")
                        .IsRequired()
                        .HasConstraintName("FK_Resenas_Paquetes");

                    b.HasOne("ToursAyacuchoPeruAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Resenas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Resenas_Usuarios");

                    b.Navigation("Paquete");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("ToursAyacuchoPeruAPI.Domain.Entities.PaqueteTuristico", "Paquete")
                        .WithMany("Reservas")
                        .HasForeignKey("PaqueteId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservas_Paquetes");

                    b.HasOne("ToursAyacuchoPeruAPI.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservas_Usuarios");

                    b.Navigation("Paquete");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Pago", b =>
                {
                    b.Navigation("Comprobante");
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.PaqueteTuristico", b =>
                {
                    b.Navigation("Resenas");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Reserva", b =>
                {
                    b.Navigation("Pago");
                });

            modelBuilder.Entity("ToursAyacuchoPeruAPI.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Bloqueo");

                    b.Navigation("Resenas");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
